config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations"}
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  root 'posts#index'

#get resources from users controller
  resources :users, only: [:show, :index]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  belongs_to :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" },
  :default_url => 'Images-icon.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

 def self.search(search)
  if search
    where(['title LIKE ?', "%#{search}%"])
  else
    all
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  validates_uniqueness_of :name

    has_attached_file :avatar, styles: { medium: "300x300#", thumb: "150x150>" }, :default_url => ActionController::Base.helpers.asset_path('head.jpeg')
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :posts
  has_many :comments

  belongs_to :users

def self.search(search)
  if search
    where(['user_id: LIKE ?', "%#{search}%"])
  else
    all
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    ProfanityChecker.swapProfanity(comment_params[:content])
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content, :avatar))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :avatar)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
    @posts = Post.search(params[:search])
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def new
    @post = current_user.posts.build
  end

  def create
    ProfanityChecker.swapProfanity(post_params[:description])
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    ProfanityChecker.swapProfanity(post_params[:description])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, :notice => "Your post has been deleted"
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image, :id, :avatar)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :current_password, :occupation, :about, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only:[:show, :index]

  def show
  	@posts = Post.where(user_id: current_user.id)
  	@most_recent = Post.where(user_id: current_user.id).last
    @counter = 0
    @like_size = 0
    @posts.each do |post|
     @counter += post.comments.size 
     @like_size += post.get_likes.size
    
  	end
  end

  def index
  @users = User.search(params[:search])
 redirect_to post_path(@post)
end

private

def set_user
  @user = User.find_by(name: params[:id])
end

def user_params
  params.require(:user).permit(:avatar, :name, :title, :link, :description, :image)
end

  def only_current_user
        @user = User.find(params[:user_id])
        redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= simple_form_for ([@post, @post.comments.build]) do |f|
  = f.input :content, label: "Reply to thread"
  = f.button :submit, value: "Leave Comment", class: "button"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-main
  .container
    %nav.navbar.navbar-default
      .navbar-header
        %button.navbar-toggle{"data-target" => ".js-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand
          = link_to "Paradigm", root_path, class: "navbar-brand"
      .navbar-collapse.js-navbar-collapse.collapse{"aria-expanded" => "false", :style => "height: 1px;"}
        .col-md-4.col-md-offset-4.search
          = form_tag root_path, :method => 'get' do
            = text_field_tag :search, params[:search]
            = submit_tag "Search"
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Add New Inspiration", new_post_path, class: "button"
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.name
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to "Profile", user_path(current_user.name)
                %li= link_to "Settings", edit_user_registration_path
                %li= link_to "Logout", destroy_user_session_path, method: :delete
          - else
            %a.btn.button{:href => "#", :onclick => "$('#LogIn').modal('show');"} Login
            %a.btn.button{:href => "#", :onclick => "$('#SignUp').modal('show');"} Sign Up

app/views/layouts/application.html.haml
!!!!5
%html
%head
  %title Paradigm
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
  = csrf_meta_tags

%body
  %header


    = render "layouts/header"
    = render "posts/login_modal"
    = render "posts/signup_modal"

%a.scrollup{:href => "#" }


.container
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert alert-success"
  = yield

app/views/posts/_edit_modal.html.haml
/ Button trigger modal
.data{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
  Edit
/ Modal
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4#myModalLabel.modal-title Edit
      .modal-body
        = render 'form'

app/views/posts/_form.html.haml
= simple_form_for @post, :html => { :class => 'post-form form-group' } do |f|
  .row
    .col-md-6
      = image_tag @post.image.url(:small)
      = f.input :image
    .col-md-6
      = f.input :title, input_html: { class: "form-control" }
    .col-md-6.link_float
      = f.input :link, input_html: { class: "form-control" }
  .row
    .col-md-12
      = f.input :description, input_html: { class: "form-control" }
      %br/
      =f.button :submit

app/views/posts/_login_modal.html.haml
#LogIn.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} &times;
        %h2.modal-title Sign In
      .modal-body
        %p Please enter your username and password
        = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          .form-group.float-label-control
            = f.input :email, required: true, autofocus: true, input_html: { class: "form-control" }
          .form-group.float-label-control
            = f.input :password, required: true, autocomplete: "off", input_html: { class: "form-control" }
          - if devise_mapping.rememberable?
            .form-group.float-label-control
              = f.check_box :remember_me
              = f.label :remember_me
          .actions
            = f.submit "Log in", class: "btn button"
      .modal-footer
        .btn.button{"data-dismiss" => "modal", :type => "button"} Close

app/views/posts/_signup_modal.haml
#SignUp.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} &times;
        %h2.modal-title Sign Up
      .modal-body
        %p Please Fill in all the required fields
        = simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          .form-group.float-label-control
            = f.input :name, required: true, autofocus: true, input_html: { class: "form-control" }
            %br/
            = f.input :email, required: true, input_html: { class: "form-control" }
          .form-group.float-label-control
            = f.input :password, required: true, input_html: { class: "form-control" }, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length)
            %br/
          .form-group.float-label-control
            = f.input :password_confirmation, required: true, input_html: { class: "form-control" }
            %br/
            .form-group 
              = f.submit "Sign Up", class: "btn button"
      .modal-footer
        .btn.button{"data-dismiss" => "modal", :type => "button"} Close

app/views/posts/index.html.haml
.container
  .row
    .col-md-12#index-text
      - if user_signed_in?
        %h2.text-center
          Hello
          = current_user.name
          %br/
          %small.text-center
            Share your inspiration and see what's inspiring others
      - else
        %h2.text-center
          What Inspires you?
          %br/
          %small.text-center
            Share your inspiration and see what's inspiring others

      .row#posts
        - @posts.each do |post|
          .col-md-4.post
            .post_image
              = link_to (image_tag post.image.url(:small)), post
              .title
                %h2= link_to post.title, post
              .data.clearfix
                %p.username
                  Shared by
                  = post.user.name
                %p.buttons
                  %span
                    %i.fa.fa-comments-o
                    = post.comments.count
                  %span
                    %i.fa.fa-thumbs-o-up
                    = post.get_likes.size

app/views/posts/new.html.haml
%h1 Add new inspiration

= render 'form'

app/views/posts/show.html.haml
.container#post_show
  .row
    .col-md-12
      %h1= @post.title
      %p.username
        Shared by
        = @post.user.name
        about
        = time_ago_in_words(@post.created_at)
        ago
      .clearfix
        .col-md-6
          = image_tag @post.image.url(:medium)
          .description= simple_format(@post.description)
        .col-md-3.post_data
          = link_to "Visit Link", @post.link, class: "button"
          = link_to like_post_path(@post), method: :get, class: "data" do
            %i.fa.fa-thumbs-o-up
            = pluralize(@post.get_upvotes.size, "Like")
          = link_to dislike_post_path(@post), method: :get, class: "data" do
            %i.fa.fa-thumbs-o-down
            = pluralize(@post.get_downvotes.size, "Dislike")
          %a#click.data{:href => "#comments" }
            %i.fa.fa-comments-o
              = pluralize(@post.comments.count, "Comment")
          - if @post.user == current_user
            .edit
            = render 'edit_modal'
            = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
        .col-md-3#random_post
          %h3 Other Inspiration
          .post
            .post_image
              = link_to (image_tag @random_post.image.url(:small)), post_path(@random_post)
            .post_content
              .title
                %h2= link_to @random_post.title, post_path(@random_post)
              .data
                %p.username
                  Shared by
                  = @random_post.user.name
                %p.buttons
                  %span
                    %i.fa.fa-comments-o
                    = @random_post.comments.count
                  %span
                    %i.fa.fa-thumbs-o-up
                    = @random_post.get_likes.size

.row
  .col-md-6#comments
    %h2.comment_count= pluralize(@post.comments.count, "Comment")
    - @comments.each do |comment|
      .comment
        = image_tag comment.user.avatar.url(:thumb)
        %p.username= comment.user.name
        %p.content= comment.content

    = render 'comments/form'

app/views/users/show.html.haml
.container{:style => "margin-top: 20px; margin-bottom: 20px;"}
  .row.panel
    .col-md-4.bg_blur
      = image_tag @most_recent.image.url
      %a.follow_btn.hidden-xs{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseExample", :role => "button"}
        Share
        #collapseExample.collapse
          .well
            .pin.social
            .twitter.social
            .insta.social
            .face.social

    .col-md-8.col-xs-12
      .img-thumbnail.picture.hidden-xs
        = image_tag @user.avatar.url(:thumb)
      .img-thumbnail.visible-xs.picture_mob
        = image_tag @user.avatar.url(:thumb)
      .profile-header
        %h2
          = @user.name
        %h4
          = @user.occupation
        %span
          = @user.about
  .row.profile-nav
    .col-md-4
    .col-md-8.col-xs-12{:style => "margin: 0px;padding: 0px;"}
      .col-md-4.col-xs-4.profile-well
        %i.fa.fa-weixin.fa-lg
        = @counter
      .col-md-4.col-xs-4.profile-well
        %i.fa.fa-heart-o.fa-lg
        14
      .col-md-4.col-xs-4.profile-well
        %i.fa.fa-thumbs-o-up.fa-lg
        = @like_size
        

.row#posts
  %h2#heading
    Added Inspirations
  - @posts.each do |post|
    .col-md-4.post
      .post_image
        = link_to (image_tag post.image.url(:small)), post
      .post_content
        .title
          %h2= link_to post.title, post
        .data.clearfix
          %p.username
            Shared by
            = post.user.name
          %p.buttons
            %span
              %i.fa.fa-comments-o
              = post.comments.count
            %span
              %i.fa.fa-thumbs-o-up
              = post.get_likes.size